# Generated by Django 5.2.11 on 2026-05-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('light', 'Light Jet'), ('midsize', 'Midsize Jet'), ('heavy', 'Heavy Jet'), ('ultra_long', 'Ultra-Long Range'), ('turboprop', 'Turboprop'), ('helicopter', 'Helicopter'), ('cargo', 'Cargo Aircraft')], max_length=20)),
                ('seats', models.PositiveSmallIntegerField()),
                ('range_km', models.PositiveIntegerField(help_text='Max range in kilometres')),
                ('max_payload_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aircraft/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('private_jet', 'Private Jet Charter'), ('group_air', 'Group Air Charter'), ('air_cargo', 'Air Cargo'), ('aircraft_leasing', 'Aircraft Leasing'), ('flight_support', 'Flight Support'), ('aes', 'Aviation Emergency Services')], help_text='Leave blank for global FAQs', max_length=30)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['service_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('service_type', models.CharField(choices=[('private_jet', 'Private Jet Charter'), ('group_air', 'Group Air Charter'), ('air_cargo', 'Air Cargo'), ('aircraft_leasing', 'Aircraft Leasing'), ('flight_support', 'Flight Support'), ('aes', 'Aviation Emergency Services')], max_length=30)),
                ('origin', models.CharField(help_text='Departure city or airport', max_length=150)),
                ('destination', models.CharField(help_text='Arrival city or airport', max_length=150)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Applicable for Air Cargo / AES requests', max_digits=10, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(blank=True, choices=[('private_jet', 'Private Jet Charter'), ('group_air', 'Group Air Charter'), ('air_cargo', 'Air Cargo'), ('aircraft_leasing', 'Aircraft Leasing'), ('flight_support', 'Flight Support'), ('aes', 'Aviation Emergency Services')], max_length=30)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
